---
title: "Exercise Lab `r stringr::str_pad(params$hand_out$lab_num,2,'left','0')` 课程作业"
subtitle: " `r glue::glue('{params$hand_out$name_chn}')` "
author: "任课教师：胡华平"
date: "`r Sys.Date()`"
#knit: `r source("R/_render_public.R")`
knit: (function(inputFile, encoding) { 
  outFile <- sub(pattern = "(.*)\\..*$", replacement = "\\1", basename(inputFile));
  out_dir <- 'public';
  rmarkdown::render(inputFile,
                    encoding=encoding,
                     output_file=file.path(dirname(inputFile), out_dir, outFile)) })
params:
  hand_out:
    value:
      lab_num: 2
      name_chn: 一元回归分析（模拟数据）
      name_eng: mote-pre-simulation
  hw_start: '2021-11-03'
  hw_end: '2021-11-23'
output:
  bookdown::word_document2:
    fig_caption: yes
    toc: no
    toc_depth: 4
    number_sections: true
    global_numbering: true
    reference_docx: template/template-word-lab-exrecise.docx
  bookdown::pdf_document2:
    latex_engine: xelatex
    template: template/HWTemplate.tex
    fig_caption: yes
    includes:
      in_header: latex/header.tex
      before_body: latex/preamble.tex
    toc: no
    toc_depth: 5
    number_sections: yes
    keep_tex: yes
  bookdown::html_document2:
    number_sections: no
    toc: yes
    fig_caption: yes
    toc_float: yes
    mathjax: local
    self_contained: no
    highlight: tango
    theme: united
  word_document:
    toc: no
    toc_depth: '4'
    reference_docx: template/template-word-lab-exrecise.docx
  html_document: default
always_allow_html: yes
documentclass: article
classoption:
- (landscape
- a4paper)
- (portrait
- a4paper)
fontsize: 12pt
thanks: 请确保按要求独立完成，遵守诚信规范！
pagestyle: headings
---

```{r global_options, echo=F,message=FALSE,warning=F}
source("R/set-global-only.R", encoding = "UTF-8")
#source("../R/load-pkg.R", encoding = "UTF-8")
require(tidyverse)
require(magrittr)
require(glue)
require(here)
require(openxlsx)
```

</br>

学生姓名：_________；学生学号：___________；专业班级：__________

</br>


# 学生信息

```{r}
id_year <- 2019
teach_year <- 2021
n_add <- 5
names_chn <- c("学号", "姓名", "分组", "班级")
names_eng <- c("id", "name", "group", "class")
df_students<- openxlsx::read.xlsx("data/students-list-2021.xlsx") %>%
  rename_all(., ~all_of(names_eng)) %>%
  tibble::add_row(id = glue("{id_year}00000{1:n_add}"),
                  name = glue("跟班0{1:n_add}"),
                  class=rep("农管1903",n_add)) %>%
  mutate(class_f = factor(str_extract(class, "(\\d{1})$"))) %>%
  arrange(class_f, id) %>%
  add_column(
    dataset = paste0(
      "dataset", 
      str_pad(1:nrow(.),width = 3,
              side = "l",pad = "0")),
    .before = "id") 
  
s <- nrow(df_students) 
```


# 模拟数据

## 真实参数

```{r}
beta2 <- 0.6
beta1 <- 17
```


$$\begin{equation}
Y_i = 17+ 0.6X_i +u_i \\
u_i \sim N(0,1)
\end{equation}$$

## 基础数据

```{r}
# get case data
ready <- openxlsx::read.xlsx("data/lab2-mento-carlo.xlsx")
n <- nrow(ready)
```

## 随机数据1

> 数据生成需要满足独立同分布假设！

```{r}
# helper function
gen_pairs <- function(..){
  ns <- nrow(df_students)
  out <-  tibble(
    u = rnorm(n = ns),
    dataset = paste0("dataset",
                     str_pad(1:ns,3,'l','0'))
  )
  return(out)
}


set.seed(20211108)
tbl_random <- ready %>%
  mutate(
    data = map(
      .x = obs, 
      .f = gen_pairs
      )) %>%
  unnest(data) %>%
  mutate(Ydata = spend+u) 
```

## 发布作业数据1

> 数据进行了4位小数显示（四舍五入），与原始数据略有差异

```{r}
# give the head for output
vars_sel <- c("dataset", "class", "id", "name", 
              "obs", "income", "Ydata")
vars_chn <-c("数据集", "班级", "学号", "姓名", 
              "样本", "收入", "支出")
# get all exercise data table
tbl_exercise <- tbl_random %>%
  left_join(., df_students, by = "dataset") %>%
  #mutate(spend = format(spend, digits = 2,
                        #nsmall = 2, trim =T)) %>%
  mutate(Ydata = round(Ydata,4)) %>%
  select(all_of(vars_sel)) %>%
  arrange(dataset, obs) %>%
  rename_all(., ~all_of(vars_chn))

# write table for lab exercise
file_path <- glue("data/lab2-monte-carlo-table-for-students-year-{teach_year}.xlsx")
openxlsx::write.xlsx(tbl_exercise, file_path,overwrite = T)
```

## 随机数据2

> 这种数据生成机制，不能需要满足独立同分布假设！

```{r}
# helper function
gen_pairs <- function(id){
  out <-  tibble(
    index = 1:nrow(ready),
    income = ready$income,
    spend = ready$spend +rnorm(n = nrow(ready)))
}

set.seed(20211108)
tbl_random <- df_students %>%
  mutate(
    data = map(
      .x = id, 
      .f = gen_pairs
      )) %>%
  unnest(data)
```


## 发布作业数据2

> 数据进行了4位小数显示（四舍五入），与原始数据略有差异

```{r}
# give the head for output
vars_sel <- c("dataset", "class", "id", "name", 
              "index", "income", "spend")
vars_chn <-c("数据集", "班级", "学号", "姓名", 
              "样本", "收入", "支出")
# get all exercise data table
tbl_exercise <- tbl_random %>%
  #mutate(spend = format(spend, digits = 2,
                        #nsmall = 2, trim =T)) %>%
  mutate(spend = round(spend,4)) %>%
  select(all_of(vars_sel)) %>%
  rename_all(., ~all_of(vars_chn))

# write table for lab exercise
file_path <- glue("data/lab2-monte-carlo-table-for-students-year-{teach_year}.xlsx")
openxlsx::write.xlsx(tbl_exercise, file_path)
```


