{
  "hash": "243fa466b123033090123687e533a4df",
  "result": {
    "markdown": "---\ntitle: \"Bookdown包`.docx`输出下的Latex公式测试\"\nsubtitle: \"评估自定义R包`xmerit`的公式显示函数\"\nauthor: \"胡华平\"\ndate: \"2023-10-21\"\n\nknit: (function(inputFile, encoding) { \n  outFile <- sub(pattern = \"(.*)\\\\..*$\", replacement = \"\\\\1\", basename(inputFile));\n  out_dir <- 'public';\n  rmarkdown::render(inputFile,\n                    encoding=encoding,\n                     output_file=file.path(dirname(inputFile), out_dir, outFile)) })\noutput:\n  bookdown::word_document2:\n    fig_caption: yes\n    toc: no\n    toc_depth: 4\n    number_sections: true\n    global_numbering: true\n    #reference_docx: template/template-word-lab-exrecise.docx\n\n---\n\n::: {.cell}\n\n:::\n\n\n\n# 测试说明\n\n## 测试环境\n\n系统环境如下：\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n               _                                \nplatform       x86_64-w64-mingw32               \narch           x86_64                           \nos             mingw32                          \ncrt            ucrt                             \nsystem         x86_64, mingw32                  \nstatus                                          \nmajor          4                                \nminor          3.1                              \nyear           2023                             \nmonth          06                               \nday            16                               \nsvn rev        84548                            \nlanguage       R                                \nversion.string R version 4.3.1 (2023-06-16 ucrt)\nnickname       Beagle Scouts                    \n```\n:::\n:::\n\n\n## 测试包的版本信息\n\n相关R包版本如下：\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n$rmarkdown\n[1]  2 24\n\n$bookdown\n[1]  0 35\n\n$xmerit\n[1]  0  0 11\n```\n:::\n:::\n\n\n\n\n## `.Rmd`文档的yaml参数\n\n```\noutput:\n  bookdown::word_document2:\n    fig_caption: yes\n    toc: no\n    toc_depth: 4\n    number_sections: true\n    global_numbering: true\n```\n\n# bookdown包`.docx`输出的公式语法\n\n## 基本语法规则\n\n`bookdown`解决的`Rmarkdown`生态下公式书写中自动标号和交叉引用的问题。\n\n对于`.docx`格式输出，`bookdown`下公式语法规则如下：\n\n- 添加公式标签（label）：`(\\#eq:your-label)`\n\n- 公式引用（cross-reference）：正文中`\\@ref(eq:your-label)`\n\n- 公式自动标号（numbering）：为确保公式自动标号，请**不要**使用双美元符号对`$$...$$`环境\n\n> **经验规则**：`bookdown::word_document2`输出`.docx`使用情境下，任何时候都不建议使用双美元符号对`$$...$$`环境。\n\n## 嵌套环境规则\n\n经测试，如下嵌套环境规则是受到支持的（也正是自定义R包`xmerit`（版本`0.0.11`）目前所采用的语法规则）：\n\n- 支持的有效单一LaTex公式环境（environment）：\n\na）`equation`环境\n\n```\n\\begin{equation}\n  ...\n\\end{equation}\n```\n\nb）`align`环境\n\n```\n\\begin{align}\n  ...\n\\end{align}\n```\n\n- 支持的有效嵌套LaTex公式环境（environment）：\n\n> a）局部对齐排列的嵌套环境\n\n\n```\n\\begin{align} \n  \\begin{split}\n   ... \n  \\end{split} \n\\end{align}\n```\n\n> b）完全对齐排列的嵌套环境\n\n```\n\\begin{equation} \n  \\begin{alignedat}{999}\n   ... \n  \\end{alignedat} \n\\end{equation}\n```\n\n\n# latex公式测试\n\n## equation（正常）\n\n```\n\\begin{equation}\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i +5\n      \\quad \\text{(equation)}\n(\\#eq:equation)\n\\end{equation}\n\n引用语法 `\\@ref(eq:equation)`显示为 \\@ref(eq:equation)。\n\n```\n\n\\begin{equation}\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i +5\n     \\quad \\text{(equation)}\n(\\#eq:equation)\n\\end{equation}\n\n引用语法 `\\@ref(eq:equation)`显示为 \\@ref(eq:equation)。\n\n## align+多公式（正常）\n\n```\n\\begin{align}\na & = b + c &&  \\text{(nodollar-align-1)} (\\#eq:align1) \\\\\nc & = d + e &&  \\text{(nodollar-align-2)} (\\#eq:align2)\n\\end{align}\n\n引用语法 `\\@ref(eq:align1)`显示为 \\@ref(eq:align1)；引用语法 `\\@ref(eq:align2)`显示为 \\@ref(eq:align2)。\n\n```\n\n\\begin{align}\na & = b + c && \\text{(align-nodollar1)} (\\#eq:align1) \\\\\nc & = d + e && \\text{(align-nodollar2)} (\\#eq:align2)\n\\end{align}\n\n\n引用语法 `\\@ref(eq:align1)`显示为 \\@ref(eq:align1)；引用语法 `\\@ref(eq:align2)`显示为 \\@ref(eq:align2)。\n\n\n## `$$`常规公式（显示公式和引用，但不显示公式标号）\n\n```\n$$\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i\n      \\quad \\text{(dollar)}\n      (\\#eq:dollar)\n$$\n\n引用语法 `\\@ref(eq:dollar)`显示为 \\@ref(eq:dollar)。\n\n```\n\n$$\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i\n      \\quad \\text{(dollar)}\n      (\\#eq:dollar)\n$$\n\n引用语法 `\\@ref(eq:dollar)`显示为 \\@ref(eq:dollar)。\n\n\n\n## `$$`+aligned\n\n```\n$$\n\\begin{aligned}\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i +5\n      \\text{(dollar-aligned)}\n(\\#eq:dollar-aligned)\n\\end{aligned}\n$$\n\n引用语法 `\\@ref(eq:dollar-aligned)`显示为 \\@ref(eq:dollar-aligned)。\n\n```\n\n$$\n\\begin{aligned}\nS_n = \\frac{X_1 + X_2 + \\cdots + X_n}{n}\n      = \\frac{1}{n}\\sum_{i}^{n} X_i +5\n      \\text{(dollar-aligned)}\n(\\#eq:dollar-aligned)\n\\end{aligned}\n$$\n\n引用语法 `\\@ref(eq:dollar-aligned)`显示为 \\@ref(eq:dollar-aligned)。\n\n\n\n## aligned（不显示公式，显示引用）\n\n```\n\\begin{aligned}\nS_n &= \\frac{X_1 + X_2 + \\cdots + X_n}{n} \\\\\n    &= \\frac{1}{n}\\sum_{i}^{n} X_i +5\n      \\text{(aligned)}\n(\\#eq:aligned)\n\\end{aligned}\n\n引用语法 `\\@ref(eq:aligned)`显示为 \\@ref(eq:aligned)。\n\n```\n\n\\begin{aligned}\nS_n &= \\frac{X_1 + X_2 + \\cdots + X_n}{n} \\\\\n    &= \\frac{1}{n}\\sum_{i}^{n} X_i +5\n      \\text{(aligned)}\n(\\#eq:aligned)\n\\end{aligned}\n\n引用语法 `\\@ref(eq:aligned)`显示为 \\@ref(eq:aligned)。\n\n\n## alignedat（不显示公式，显示引用）\n\n```\n\\begin{alignedat}{999}\n&\\widehat{mpg}=&&+43.54&&-1.78cyl_i&&+0.01disp_i\\\\ \n&(s)&&(4.8601)&&(0.6139)&&(0.0120)\\\\ \n&(t)&&(+8.96)&&(-2.91)&&(+0.58)\\\\ \n&(cont.)&&-3.79wt_i&&-0.49gear_i &&\\\\ \n&(s)&&(1.0818)&&(0.7903) &&\\\\ \n&(t)&&(-3.51)&&(-0.62) &&\n\\quad \\text{(alignedat)}\\quad\n(\\#eq:alignedat)\n\\end{alignedat}\n\n引用语法 `\\@ref(eq:alignedat)`显示为 \\@ref(eq:alignedat)。\n\n```\n\n\\begin{alignedat}{999}\n&\\widehat{mpg}=&&+43.54&&-1.78cyl_i&&+0.01disp_i\\\\ \n&(s)&&(4.8601)&&(0.6139)&&(0.0120)\\\\ \n&(t)&&(+8.96)&&(-2.91)&&(+0.58)\\\\ \n&(cont.)&&-3.79wt_i&&-0.49gear_i &&\\\\ \n&(s)&&(1.0818)&&(0.7903) &&\\\\ \n&(t)&&(-3.51)&&(-0.62) && \n\\quad \\text{(alignedat)}\\quad\n(\\#eq:alignedat)\n\\end{alignedat}\n\n引用语法 `\\@ref(eq:alignedat)`显示为 \\@ref(eq:alignedat)。\n\n\n\n# xmerit包公式语法\n\n## 数据集\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mod, data = df)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-4.916 -1.248 -0.357  1.472  5.925 \n\nCoefficients:\n            Estimate Std. Error t value     Pr(>|t|)\n(Intercept) 43.53985    4.86006    8.96 0.0000000014\ncyl         -1.78430    0.61389   -2.91       0.0072\ndisp         0.00694    0.01201    0.58       0.5678\nwt          -3.79287    1.08182   -3.51       0.0016\ngear        -0.49045    0.79029   -0.62       0.5401\n               \n(Intercept) ***\ncyl         ** \ndisp           \nwt          ** \ngear           \n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.6 on 27 degrees of freedom\nMultiple R-squared:  0.835,\tAdjusted R-squared:  0.811 \nF-statistic: 34.1 on 4 and 27 DF,  p-value: 0.000000000336\n```\n:::\n:::\n\n\n## xmerit::lx.psm（align+split）\n\n`xmerit::lx.psm()`函数默认形式为嵌套结构`\\begin{align}`内含`\\begin{split}`。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlx.out <- xmerit::lx.psm(\n  x = xvars, y = yvars,\n  begin = 0,\n  #greek.n = length(xvars)+1,\n  n.row = 3,\n  lm.label = \"lx-psm\",\n  lm.tag = \"(lx.psm)\",\n  no_dollar = TRUE)\n```\n:::\n\n\n```\n\\begin{align}\n\\begin{split}\nmpg_i=&+\\beta_{0}+\\beta_{1}cyl_i+\\beta_{2}disp_i\\\\&+\\beta_{3}wt_i+\\beta_{4}gear_i+u_i\n\\end{split}\n\\quad \\text{(lx.psm)}\\quad\n(\\#eq:lx-psm)\n\\end{align}\n\n引用语法 `\\@ref(eq:lx-psm)`显示为 \\@ref(eq:lx-psm)。\n\n```\n\n\\begin{align}\n\\begin{split}\nmpg_i=&+\\beta_{0}+\\beta_{1}cyl_i+\\beta_{2}disp_i\\\\&+\\beta_{3}wt_i+\\beta_{4}gear_i+u_i\n\\end{split}\n\\quad \\text{(lx.psm)}\\quad\n(\\#eq:lx-psm)\n\\end{align}\n\n引用语法 `\\@ref(eq:lx-psm)`显示为 \\@ref(eq:lx-psm)。\n\n\n## xmerit::lx.est（equation + alignedat）\n\n`xmerit::lx.est()`函数默认形式为嵌套结构`\\begin{equation}`内含`\\begin{alignedat}{999}`。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlx.out <- lx.est(lm.mod = mod,lm.dt = df,lm.n = 3,lm.label = \"lx-est\", lm.tag = \"lx.est\",\n                 no_dollar = TRUE)\n```\n:::\n\n\n\\begin{equation}\n\\begin{alignedat}{999}\n&\\widehat{mpg}=&&+43.54&&-1.78cyl_i&&+0.01disp_i\\\\ \n&(s)&&(4.8601)&&(0.6139)&&(0.0120)\\\\ \n&(t)&&(+8.96)&&(-2.91)&&(+0.58)\\\\ \n&(cont.)&&-3.79wt_i&&-0.49gear_i &&\\\\ \n&(s)&&(1.0818)&&(0.7903) &&\\\\ \n&(t)&&(-3.51)&&(-0.62) &&\n\\end{alignedat}\n\\quad \\text{(lx.est)}\\quad\n(\\#eq:lx-est)\n\\end{equation}\n\n引用语法 `\\@ref(eq:lx-est)`显示为 \\@ref(eq:lx-est)。\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}